server:
  port: 9090
spring:
  application:
    name: InventoryTracking
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: J$4abdulla
    url: jdbc:mysql://localhost:3306/capstone
    username: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/