server:
  port: 9000

spring:
  application:
    name: ordermanager
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/capstone
    username: root
    password: J$4abdulla
hibernate:
  transaction:
    jta:
      platform: enabled
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
